os: linux
language: rust
rust:
  - stable
  - beta
before_script:
  - rustup component add clippy
script:
  - make test
deploy:
  provider: cargo
  token: "$CRATES_TOKEN"
  on:
    branch: master
    tags: true
