[package]
name = "sectxtcov"
version = "0.0.4"
authors = ["eikendev"]
edition = "2018"
description = "A tool for determining the coverage of the security.txt standard."
homepage = "https://github.com/eikendev/sectxtcov"
repository = "https://github.com/eikendev/sectxtcov.git"
readme = "README.md"
license = "ISC"

[dependencies]
futures = ">=0.3.5"
reqwest = ">=0.10.6"

[dependencies.clap]
version = ">=2.31"
features = ["yaml"]

[dependencies.tokio]
version = ">=0.2"
features = ["macros"]
