[package]
name = "sectxt"
version = "0.0.4"
authors = ["eikendev"]
edition = "2018"
description = "A tool for working with security.txt files"
homepage = "https://github.com/eikendev/sectxt"
repository = "https://github.com/eikendev/sectxt.git"
readme = "README.md"
license = "ISC"

[dependencies]
futures = ">=0.3.5"
reqwest = ">=0.10.6"

[dependencies.clap]
version = ">=2.31"
features = ["yaml"]

[dependencies.tokio]
version = ">=0.2"
features = ["macros"]
